apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: castai
  namespace: flux-system
spec:
  interval: 1m
  path: "./fluxcd/helmreleases"
  prune: true
  sourceRef:
    kind: GitRepository
    name: git-source
  timeout: 2m
  wait: true








