apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cluster-controller
  namespace: castai-agent
spec:
  interval: 5m
  chart:
    spec:
      chart: castai-cluster-controller
      sourceRef:
        kind: HelmRepository
        name: castai-helm
        namespace: flux-system
  values:
    castai:
      apiKeySecretRef: castai-agent
      clusterIDSecretRef: castai-agent-metadata
