apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: castai-pod-pinner
  namespace: castai-agent
spec:
  interval: 5m
  chart:
    spec:
      chart: castai-pod-pinner
      sourceRef:
        kind: HelmRepository
        name: castai-helm
        namespace: flux-system
  values:
    envFrom:
      - secretRef:
          name: castai-agent
      - configMapRef:
          name: castai-agent-metadata

