apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cluster-controller
  namespace: castai-agent
spec:
  interval: 5m
  chart:
    spec:
      chart: castai-cluster-controller
      sourceRef:
        kind: HelmRepository
        name: castai-helm
        namespace: flux-system
      version: 0.81.8
  values:
    envFrom:
      - secretRef:
          name: castai-agent
      - configMapRef:
          name: castai-agent-metadata
    autoscaling:
      enabled: true
