apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: castai-evictor
  namespace: castai-agent
spec:
  interval: 5m
  chart:
    spec:
      chart: castai-evictor
      sourceRef:
        kind: HelmRepository
        name: castai-helm
        namespace: flux-system
  values:
    replicaCount: 1
