apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: castai-workload-autoscaler
  namespace: castai-agent
spec:
  interval: 5m
  chart:
    spec:
      chart: castai-workload-autoscaler
      sourceRef:
        kind: HelmRepository
        name: castai-helm
        namespace: flux-system
  values:
    castai:
      apiKeySecretRef: castai-agent
      configMapRef: castai-agent-metadata
