apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - castai-agent.yaml
  - castai-helm-repo.yaml
  - castai-cluster-controller.yaml
#  - castai-spot-handler.yaml
#  - castai-pod-pinner.yaml
#  - castai-kvisor.yaml
